spring:
  application:
    name: apigw
  zipkin:
    base-url: http://localhost:9411
#  cloud:
#    gateway:
#      routes:
#        - id: customer
#          uri: lb://CUSTOMER
#          predicates:
#            - Path=cc/api/v1/customers/**
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
